- src/apis/axios.ts
- src/components/layouts/ProtectedRoutes/ProtectedAdminRoutes.tsx
- src/pages/LoginPage/Login.routes.tsx
- src/pages/admin/DashboardPage/index.tsx
- Call refresh token when access token is expired
- prevent multiple refreshToken request
> feat/JWT: handle refresh token with axios interceptor

- src/components/elements/Header/components/ActionGroup/index.tsx
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Header/index.tsx
- src/components/elements/Lists/ProductList/index.tsx
- src/components/elements/Lists/ProductList/useProductList.ts
- src/components/layouts/ProtectedRoutes/ProtectedAdminRoutes.tsx
- src/output.css
- src/pages/HomePage/components/CategorySlider/index.tsx
- src/pages/HomePage/components/CategorySlider/useCategorySlider.ts
- src/pages/ProductList/ProductList.routes.tsx
- src/pages/ProductList/components/Breadcrumb/index.tsx
- src/pages/ProductList/components/Filter/index.tsx
- src/pages/ProductList/components/ListProducts/index.tsx
- src/pages/ProductList/index.tsx
- src/pages/ProductList/useProductListPage.ts
- src/routes/index.tsx
- src/types/product.type.ts
Product List Page includes:
- Filter
- Product List
> Fe 9 product page: Added UI for Product List Page

- src/components/elements/Breadcrumb/index.tsx
- src/components/elements/Cards/ProductCard/index.tsx
- src/components/elements/Lists/ProductList/index.tsx
- src/components/elements/Slider/ProductSlider/index.tsx
- src/output.css
- src/pages/HomePage/index.tsx
- src/pages/ProductDetail/ProductDetail.routes.tsx
- src/pages/ProductDetail/components/ImageSlider/index.tsx
- src/pages/ProductDetail/components/ProductFeatures/index.tsx
- src/pages/ProductDetail/components/ProductInfo/index.tsx
- src/pages/ProductDetail/components/ShopInfo/index.tsx
- src/pages/ProductDetail/index.tsx
- src/pages/ProductList/components/ListProducts/index.tsx
- src/pages/ProductList/index.tsx
- src/pages/ProductList/useProductListPage.ts
- src/routes/index.tsx
Product Detail Page includes:
- Product Information
- Store Information
- Recommend Product List
> Fe 10 product details: Added UI for Product Detail Page

- src/components/elements/NumberInput/index.tsx
- src/output.css
- src/pages/CartPage/CartPage.routes.tsx
- src/pages/CartPage/components/CartDetail/index.tsx
- src/pages/CartPage/components/CartItem/index.tsx
- src/pages/CartPage/components/Summary/index.tsx
- src/pages/CartPage/index.tsx
- src/pages/CartPage/useCartPage.ts
- src/routes/index.tsx
Cart Page includes: 
- Cart List
- Cart Item
- Recommend Product List
> Fe 11 cart: Added UI for Cart Page

- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/output.css
- src/pages/CartPage/useCartPage.ts
- src/pages/CheckoutPage/CheckoutPage.routes.tsx
- src/pages/CheckoutPage/components/CheckoutDetail/index.tsx
- src/pages/CheckoutPage/components/CheckoutItem/index.tsx
- src/pages/CheckoutPage/components/PaymentMethod/index.tsx
- src/pages/CheckoutPage/components/ReceiverAddress/components/AddressModal/Address.constants.ts
- src/pages/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressForm/index.tsx
- src/pages/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressForm/useAddressFrom.ts
- src/pages/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressItem/index.tsx
- src/pages/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressList/index.tsx
- src/pages/CheckoutPage/components/ReceiverAddress/components/AddressModal/index.tsx
- src/pages/CheckoutPage/components/ReceiverAddress/index.tsx
- src/pages/CheckoutPage/components/ShipmentInfo/index.tsx
- src/pages/CheckoutPage/index.tsx
- src/routes/index.tsx
Checkout Page includes:
- Receiver Address
- Checkout Items
- Shipment Cost
- Payment Method
> Fe 12 checkout: Added UI for Checkout Page

- src/output.css
- src/pages/ProductDetail/components/ShopInfo/index.tsx
- src/pages/StoreProfilePage/StoreProfilePage.routes.tsx
- src/pages/StoreProfilePage/components/ReviewItem/index.tsx
- src/pages/StoreProfilePage/components/ReviewList/index.tsx
- src/pages/StoreProfilePage/index.tsx
- src/routes/index.tsx
Shop Page includes: 
- Shop Information
- Shop's Products
- Shop Reviews
> Fe 13 shop: Added UI for Shop Page

- src/components/elements/Header/components/ActionGroup/index.tsx
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/output.css
- src/pages/customer/StoreRegisterPage/StoreRegisterPage.routes.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/StoreRegister.constants.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/useStoreRegisterForm.ts
- src/pages/customer/StoreRegisterPage/index.tsx
- src/routes/index.tsx
Store Register Page includes: 
- Register form
> FE-14: Added plain UI for Store Register Page

- package-lock.json
- package.json
- src/output.css
- src/pages/customer/CartPage/components/CartDetail/index.tsx
- src/pages/customer/CartPage/index.tsx
- src/pages/customer/CheckoutPage/components/CheckoutDetail/index.tsx
- src/pages/customer/CheckoutPage/index.tsx
- src/pages/seller/Dashboard/Dashboard.routes.tsx
- src/pages/seller/Dashboard/index.tsx
- src/pages/seller/components/MenuBar/index.tsx
- src/pages/seller/index.tsx
- src/routes/index.tsx
Store Dashboard includes: 
- Product Statistics
- Order Statistics
- Charts
> FE-15: Added plain UI for Store Dashboard

- src/apis/product.api.ts
- src/components/elements/Cards/ProductCard/index.tsx
- src/constants/apiPaths/productPaths.ts
- src/output.css
- src/pages/ProductDetail/ProductDetail.routes.tsx
- src/pages/ProductDetail/components/ProductFeatures/index.tsx
- src/pages/ProductDetail/components/ProductInfo/index.tsx
- src/pages/ProductDetail/components/ShopInfo/index.tsx
- src/pages/ProductDetail/index.tsx
- src/pages/ProductDetail/useProductDetail.ts
- src/types/product.type.ts
- src/types/store.type.ts
Added data fetching for product info components.
> FE-10: Fetched data of single product

- src/apis/product.api.ts
- src/components/elements/Cards/ProductCard/index.tsx
- src/output.css
- src/pages/ProductList/ProductList.routes.tsx
- src/pages/ProductList/components/Filter/components/CategoryFilter/index.tsx
- src/pages/ProductList/components/Filter/components/PriceFilter/index.tsx
- src/pages/ProductList/components/Filter/components/QualityFilter/index.tsx
- src/pages/ProductList/components/Filter/index.tsx
- src/pages/ProductList/components/ListProducts/index.tsx
- src/pages/ProductList/components/NoProduct/index.tsx
- src/pages/ProductList/components/Pagination/index.tsx
- src/pages/ProductList/components/Sort/index.tsx
- src/pages/ProductList/index.tsx
- src/pages/ProductList/useProductListPage.ts
- src/types/params/getAllProduct.params.ts
Products can be filtered by: 
- Price
- Quality
Products con be sorted by:
- Price
- Create date
Pagination is also added.
> Fe 9 product page: Added filter and sort to Product List Page

- src/apis/product.api.ts
- src/components/elements/Lists/ProductList/index.tsx
- src/components/elements/Lists/ProductList/useProductList.ts
- src/components/elements/Slider/ProductSlider/index.tsx
- src/output.css
- src/pages/HomePage/HomePage.routes.tsx
- src/pages/HomePage/components/CategorySlider/index.tsx
- src/pages/HomePage/index.tsx
- src/pages/HomePage/useHomePage.ts
- src/pages/ProductDetail/index.tsx
- src/pages/ProductList/components/Filter/components/PriceFilter/index.tsx
- src/pages/ProductList/components/Filter/index.tsx
- src/pages/ProductList/components/Sort/index.tsx
- src/pages/ProductList/useProductListPage.ts
- src/pages/StoreProfilePage/index.tsx
- src/pages/customer/CartPage/index.tsx
Fetched data for:
- Newest Products
- Free Products
> FE-8: Fetched data for Product Sliders

- src/apis/product.api.ts
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Lists/ProductList/useProductList.ts
- src/pages/HomePage/useHomePage.ts
- src/pages/ProductDetail/ProductDetail.routes.tsx
- src/pages/ProductDetail/components/ShopInfo/index.tsx
- src/pages/ProductDetail/index.tsx
- src/pages/ProductDetail/useProductDetail.ts
- src/pages/ProductList/components/Sort/index.tsx
- src/pages/ProductList/useProductListPage.ts
- src/routes/index.tsx
- src/types/category.type.ts
- src/types/product.type.ts
- src/types/store.type.ts
- src/types/user.type.ts
Data including:
- Product information
- Seller information
- Store products
> FE-10: Fetched data for Product Detail Page

- src/pages/customer/CheckoutPage/components/CheckoutDetail/index.tsx
- src/pages/customer/CheckoutPage/components/CheckoutItem/index.tsx
- src/pages/customer/CheckoutPage/components/PaymentMethod/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/index.tsx
- src/pages/customer/CheckoutPage/index.tsx
Fetched data for checkout item
> FE-12: Fetched data for Checkout page

- src/pages/customer/CheckoutPage/components/CheckoutDetail/index.tsx
- src/pages/customer/CheckoutPage/components/PaymentMethod/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressItem/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressList/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/index.tsx
Convert Cart data format into Order data format
> FE-12: Formatted mock data for COD Orders

- src/components/elements/ListItem/OrderItem/index.tsx
- src/components/elements/Lists/OrderList/index.tsx
- src/output.css
- src/pages/customer/AccountPage/StoreManagement/StoreOrder/StoreOrder.routes.tsx
- src/pages/customer/AccountPage/StoreManagement/StoreOrder/index.tsx
- src/pages/customer/AccountPage/components/MenuBar/index.tsx
- src/routes/index.tsx
Store Order Page includes:
- Order list
- Order items
> FE-17: Added plain UI for Store Order Page

- src/apis/user.api.ts
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Header/components/UserInfoGroup/useUserInfo.ts
- src/components/elements/Header/index.tsx
- src/constants/apiPaths/userPaths.ts
- src/pages/customer/AccountPage/Profile/Profile.constants.ts
- src/pages/customer/AccountPage/Profile/components/ProfileForm/index.tsx
- src/pages/customer/AccountPage/Profile/components/ProfileForm/useProfileForm.ts
User Profile Form includes:
- First name: required
- Last name: required
- Email: noneditable
- Phone number: 10 characters, required,
- Date of birth: date
> FE-7: Added update user profile feature

- src/apis/address.api.ts
- src/apis/store.api.ts
- src/apis/user.api.ts
- src/components/elements/ControlledComponents/ControlledTextArea/index.tsx
- src/components/elements/Header/components/ActionGroup/index.tsx
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Header/components/UserInfoGroup/useUserInfo.ts
- src/output.css
- src/pages/StoreProfilePage/components/UserInfo/index.tsx
- src/pages/StoreProfilePage/index.tsx
- src/pages/StoreProfilePage/useUserProfileName.ts
- src/pages/customer/AccountPage/Profile/components/ProfileForm/useProfileForm.ts
- src/pages/customer/AccountPage/Profile/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/StoreRegister.constants.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/useStoreRegisterForm.ts
- src/pages/customer/StoreRegisterPage/index.tsx
- src/routes/index.tsx
> FE-14: Added register function

- src/components/elements/Form/AddressForm/index.tsx
- src/components/elements/Form/AddressForm/useAddressForm.ts
- src/pages/customer/AccountPage/Address/components/AddressItem/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressList/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressModal/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressModal/useAddressModal.ts
- src/pages/customer/AccountPage/Address/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressForm/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressForm/useAddressFrom.ts
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/StoreRegister.constants.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/useStoreRegisterForm.ts
- src/types/address.type.ts
- src/types/http/store.type.ts
- src/types/store.type.ts
Change address form from local component to shared component
> refactor: added changes to receiver address form

- src/apis/cart.api.ts
- src/pages/ProductDetail/components/ProductFeatures/index.tsx
- src/pages/ProductDetail/components/ProductInfo/index.tsx
- src/pages/ProductDetail/components/ShopInfo/index.tsx
- src/pages/ProductDetail/index.tsx
- src/pages/ProductDetail/useProductDetail.ts
- src/pages/customer/CartPage/components/CartDetail/index.tsx
- src/pages/customer/CartPage/components/CartItem/index.tsx
- src/pages/customer/CartPage/index.tsx
- src/pages/customer/CartPage/useCartPage.ts
Actions after "Buy Now" button clicked:
- Add product to cart
- Navigate to Cart Page
- Check the buy-now product
> feat: Added Buy now button handler

- src/apis/user.api.ts
- src/components/elements/Form/AddressForm/index.tsx
- src/output.css
- src/pages/customer/AccountPage/Address/components/AddressItem/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressItem/useAddressItem.ts
- src/pages/customer/AccountPage/Address/components/AddressModal/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressModal/useAddressModal.ts
- src/pages/customer/AccountPage/Address/index.tsx
- src/pages/customer/AccountPage/useAccountPage.ts
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressForm/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressForm/useAddressFrom.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/useStoreRegisterForm.ts
> refactor: Added "Add address" function for user

- src/components/elements/ControlledComponents/ControlledDropDown/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/useStoreRegisterForm.ts
- Auto fill when choosing recommended address
> refactor: Updated Store register form UI

- src/pages/HomePage/components/CategorySlider/index.tsx
- src/pages/admin/DashboardPage/Dashboard.routes.tsx
- src/pages/customer/AccountPage/StoreManagement/StoreOrder/StoreOrder.routes.tsx
- src/pages/customer/AccountPage/StoreManagement/StoreProfile/StoreProfile.routes.tsx
- src/pages/customer/AccountPage/StoreManagement/StoreProfile/index.tsx
- src/pages/customer/AccountPage/StoreManagement/StoreProfile/useStoreProfileForm.ts
- src/routes/index.tsx
Store Profile Page includes:
- Store Profile Form
- Avatar Uploader
> FE-18: Added plain UI for Store Profile Page

- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/output.css
- src/pages/customer/AccountPage/Profile/index.tsx
- src/pages/customer/AccountPage/components/MenuBar/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/useStoreRegisterForm.ts
Preconditions:
- Users must update their profile
- There's a confirm modal for users to decide whether they want to update their profile or not
Register Form:
- Users can choose their store address based on their addresses, or they can define a new one
Actions after submission:
- User will be navigated to their page
- User will access system as seller
- Use is no longer accessible to this Store Register Page
> feat: Added Store Register Function

- src/apis/user.api.ts
- src/pages/customer/AccountPage/Address/components/AddressItem/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressItem/useAddressItem.ts
- src/pages/customer/AccountPage/Address/components/AddressList/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressModal/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressModal/useAddressModal.ts
- src/pages/customer/AccountPage/Address/index.tsx
- src/pages/customer/AccountPage/useAccountPage.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/types/http/address.type.ts
- src/types/user.type.ts
> feat: Added update address function

- src/components/elements/ControlledComponents/ControlledInput/index.tsx
- src/output.css
- src/pages/customer/UploadProductPage/UploadProductPage.routes.tsx
- src/pages/customer/UploadProductPage/components/ConditionRadio/index.tsx
- src/pages/customer/UploadProductPage/components/ProductForm/ProductForm.constants.ts
- src/pages/customer/UploadProductPage/components/ProductForm/index.tsx
- src/pages/customer/UploadProductPage/components/ProductForm/useProductForm.ts
- src/pages/customer/UploadProductPage/index.tsx
- src/pages/customer/UploadProductPage/useUploadProductPage.ts
- src/routes/index.tsx
- src/types/enum/productQuality.enum.ts
Upload Product Page includes:
- Product Form
- Images Uploader
- Category Dropdown
- Quality Radio Group
> FE-20: Added palin UI for Upload Product Page

- src/output.css
- src/pages/customer/AccountPage/Address/components/AddressItem/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressItem/useAddressItem.ts
- src/pages/customer/AccountPage/Address/components/AddressList/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressModal/index.tsx
- src/pages/customer/AccountPage/Address/components/AddressModal/useAddressModal.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/index.tsx
- src/types/user.type.ts
Updated address object assessment from 3 levels down to 2 levels
> refactor: Updated address object assessment

- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Header/index.tsx
- src/pages/customer/AccountPage/components/MenuBar/index.tsx
- src/redux/slices/login.slice.ts
After logging out, user will be nagivated to home page
> feat: Added log out function

- src/components/elements/Cards/ProductCard/index.tsx
- src/components/elements/Form/ProductForm/ProductForm.constants.ts
- src/components/elements/Form/ProductForm/index.tsx
- src/components/elements/Form/ProductForm/useProductForm.ts
- src/pages/customer/StoreProductDetailPage/index.tsx
- src/pages/customer/StoreProductDetailPage/useStoreProductForm.ts
- src/types/address.type.ts
- src/types/http/product.type.ts
- src/types/product.type.ts
Added size and address property:
> feat: updated product's fields for upload and update function

- src/apis/user.api.ts
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/constants/urlPaths/guestUrls.ts
- src/pages/ProductDetail/components/ShopInfo/index.tsx
- src/pages/StoreProfilePage/useUserProfileName.ts
- src/pages/customer/CartPage/components/CartItem/index.tsx
- src/pages/customer/CartPage/components/CartItem/useCartItem.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/StoreRegister.constants.ts
- src/types/user.type.ts
User will see others' slug on site's search bar instead of ID
> feat: Added get user profile by slug

- src/components/elements/Cards/ProductCard/index.tsx
- src/components/elements/Form/ProductForm/components/CategoryDropdown/index.tsx
- src/components/elements/Form/ProductForm/components/ImageUploader/index.tsx
- src/components/elements/Form/ProductForm/components/ImageUploader/useImageUploader.ts
- src/components/elements/Form/ProductForm/index.tsx
- src/components/elements/Form/ProductForm/useProductForm.ts
- src/output.css
- src/pages/HomePage/components/CategorySlider/index.tsx
- src/pages/ProductDetail/components/ImageSlider/index.tsx
- src/pages/ProductDetail/components/ProductInfo/index.tsx
- src/pages/customer/AccountPage/index.tsx
- src/pages/customer/CartPage/components/CartDetail/index.tsx
- src/pages/customer/CheckoutPage/components/CheckoutDetail/index.tsx
- src/pages/customer/StoreProductsPage/index.tsx
- src/types/category.type.ts
User click the upload button to add a new image:
An image editor will appear whenever the user adds a new image: 
Hover and click the 'eye' button to preview the image. Hover and click the 'trash bin' button to delete the image:
The image list will be sent with others form's information when the user clicks the submit button.
> Fe-8: Added upload image for product function

- src/components/elements/Form/ProductForm/components/CategoryDropdown/index.tsx
- src/components/elements/Form/ProductForm/index.tsx
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Header/index.tsx
- src/components/elements/Menu/CategoryMenu/index.tsx
- src/components/elements/Menu/CategoryMenu/useCategoryMenu.ts
- src/output.css
- src/pages/customer/CustomerAddressPage/components/AddressModal/index.tsx
- src/pages/customer/CustomerProfilePage/components/PhoneModal/components/VerifyOTPForm/index.tsx
- src/pages/customer/CustomerProfilePage/components/PhoneModal/components/VerifyOTPForm/useVerifyOTPForm.ts
- src/pages/customer/CustomerProfilePage/components/PhoneModal/index.tsx
- src/types/category.type.ts
- src/types/user.type.ts
> feat: Updated category menu display

- src/components/elements/Form/ProductForm/ProductForm.constants.ts
- src/output.css
- src/pages/customer/CheckoutPage/components/CheckoutItem/index.tsx
- src/pages/customer/CheckoutPage/components/PaymentMethod/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/components/ShipModal/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/components/ShipModal/useShipmentModal.ts
- src/pages/customer/CheckoutPage/components/ShipmentInfo/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/useShipment.ts
- src/pages/customer/CheckoutPage/index.tsx
- src/pages/customer/CheckoutPage/useCheckoutPage.ts
- src/pages/customer/StoreRegisterPage/components/StoreRegisterForm/useStoreRegisterForm.ts
- src/types/http/order.type.ts
User can choose from existing methods:
> feat: Added choosing shipment method function

- src/apis/order.api.ts
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Header/components/UserInfoGroup/useUserInfo.ts
- src/constants/apiPaths/orderPaths.ts
- src/output.css
- src/pages/customer/CartPage/components/CartDetail/index.tsx
- src/pages/customer/CartPage/components/CartItem/index.tsx
- src/pages/customer/CartPage/components/SoldoutProducts/index.tsx
- src/pages/customer/CartPage/index.tsx
- src/pages/customer/CartPage/useCartPage.ts
- src/pages/customer/CheckoutPage/components/CheckoutItem/index.tsx
- src/pages/customer/CheckoutPage/components/PaymentMethod/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/components/ShipModal/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/components/ShipModal/useShipmentModal.ts
- src/pages/customer/CheckoutPage/components/ShipmentInfo/index.tsx
- src/pages/customer/CheckoutPage/components/ShipmentInfo/useShipment.ts
- src/pages/customer/CheckoutPage/index.tsx
- src/pages/customer/CheckoutPage/useCheckoutPage.ts
- src/pages/customer/StoreProductsPage/index.tsx
- User can change receiver address: 
- User can choose shipment method:
- After placing order, product in cart will be removed and user will be navigate to order list page
> feat: Added place order function

- src/apis/user.api.ts
- src/pages/admin/AccountListPage/AccountListPage.routes.tsx
- src/pages/admin/AccountListPage/index.tsx
- src/pages/admin/AdminLayout/components/MenuBar/index.tsx
- src/pages/admin/AdminLayout/index.tsx
- src/pages/admin/DashboardPage/index.tsx
- src/pages/admin/OrderListPage/OrderListPage.routes.tsx
- src/pages/admin/OrderListPage/index.tsx
- src/pages/admin/ProductListPage/ProductListPage.routes.tsx
- src/pages/admin/ProductListPage/index.tsx
- src/pages/customer/AccountPage/components/MenuBar/index.tsx
- src/pages/customer/CustomerAddressPage/components/AddressItem/index.tsx
- src/routes/account.routes.tsx
- src/routes/admin.routes.tsx
- src/routes/index.tsx
Admin pages include:
- Dashboard
- Account List
- Order List
- Product List
> feat: Added plain UI for Admin pages

- src/apis/admin.api.ts
- src/components/elements/Header/components/UserInfoGroup/index.tsx
- src/components/elements/Header/index.tsx
- src/output.css
- src/pages/LoginPage/Login.constant.ts
- src/pages/LoginPage/components/LoginForm/index.tsx
- src/pages/LoginPage/components/LoginForm/useLoginForm.ts
- src/pages/NotFoundPage/index.tsx
- src/pages/SignupPage/components/SignupForm/Signup.constant.ts
- src/pages/SignupPage/components/SignupForm/index.tsx
- src/pages/SignupPage/components/SignupForm/useSignupForm.ts
- src/pages/SignupPage/components/VerifyOTPForm/useVerifyOTPForm.ts
- src/pages/StoreProfilePage/components/UserInfo/index.tsx
- src/pages/admin/AdminLayout/components/MenuBar/index.tsx
- src/pages/admin/DashboardPage/index.tsx
- src/pages/admin/OrderListPage/index.tsx
- src/pages/customer/AccountPage/components/MenuBar/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/components/AddressModal/components/AddressItem/index.tsx
- src/pages/customer/CheckoutPage/components/ReceiverAddress/index.tsx
- src/pages/customer/CheckoutPage/useCheckoutPage.ts
- src/pages/customer/CustomerAddressPage/components/AddressItem/index.tsx
- src/pages/customer/CustomerProfilePage/components/ProfileForm/index.tsx
- src/pages/customer/StoreProductsPage/useStoreProducts.ts
- src/types/http/login.type.ts
- src/types/http/signup.type.ts
- src/types/http/verifyOTP.type.ts
- src/utils/formatName.ts
- src/utils/formattedAddress.ts
- Changed email field to phone number field
> refactor: Updated authentication from using email to using phone number
